### ISSUE TITLE
Hiding unneeded entries "such as integrated GPU"

### ISSUE THREAD

**Issue by YamiYukiSenpai** [jsalatas/plasma-pstate#14]
For those of us with dedicated GPUs, would it be possible to hide the GPU entry, or at least allow us to hide it?

------------------

Off-topic: the GitHub repo should include how to update the extension, just like in your KDE store page.

**Comment by jsalatas** [comment]
Could you please verify and if everything is ok close the issue?

Thanks for you help!

**Comment by YamiYukiSenpai** [comment]
My desktop has NVIDIA GPU.  I don't wanna call it a "waste of space", but seeing it there bothers me because it's disabled.
![screenshot_20190227_032526](https://user-images.githubusercontent.com/13153124/53475979-5383ad80-3a3f-11e9-82d1-d57b368c9974.png)

**Comment by jsalatas** [comment]
Could you please checkout the latest code? I have added an option to hide it. I'm just asking you to confirm that this working for you. 
Thanks!

**Comment by YamiYukiSenpai** [comment]
I assumed it wasn't released yet because it wasn't in the release section

I'll pull from master now

**Comment by YamiYukiSenpai** [comment]
Didn't work

![screenshot_20190227_034701](https://user-images.githubusercontent.com/13153124/53477281-57fd9580-3a42-11e9-997b-b02307e15501.png)

**Comment by jsalatas** [comment]
Could you please remove the widget and then add it again?
BTW: there is a setting that you need to uncheck for this to work

**Comment by YamiYukiSenpai** [comment]
I did do that
BTW, reboot fixed it
![screenshot_20190227_123445](https://user-images.githubusercontent.com/13153124/53510472-11348d80-3a8c-11e9-80de-43e801fad956.png)

**Comment by jsalatas** [comment]
OK. Thanis!
