### ISSUE TITLE
Plasmoid window empty when clicked but shows info when hovering over icon

### ISSUE THREAD

**Issue by richterlevania3** [jsalatas/plasma-pstate#17]
![Screenshot_20190325_144456](https://user-images.githubusercontent.com/12630253/54941960-e0ba0500-4f0c-11e9-82c3-50cab1d4a584.png)

**Comment by jsalatas** [comment]
What happens when you run the following command? Does it ask you for a password? 

`sudo /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh -read-all
`

**Comment by richterlevania3** [comment]
sudo doesn't work for me
I must su into root first, then the following shows up.

![Screenshot_20190325_172636](https://user-images.githubusercontent.com/12630253/54951884-72cd0800-4f23-11e9-81f8-268ad9ebee93.png)

**Comment by jsalatas** [comment]
The application requires you to be able to execute scripts via sudo. You should add yourself to the sudoers file.
