### ISSUE TITLE
OpenSuse Thumbleweed. Menu is black, all gui elements misssing

### ISSUE THREAD

**Issue by christianwn** [jsalatas/plasma-pstate#19]
When you click the icon only the background color of the box is shown, all the buttons and stuff is missing. However mouse over the program button and you see the frequency and %.

**Comment by jsalatas** [comment]
Are you using KDE desktop?

**Comment by christianwn** [comment]
Thanks for quick reply, yes KDE. Adding my user to group wheel solved the problem.
