### ISSUE TITLE
Installing in Linux Mint Cinnamon

### ISSUE THREAD

**Issue by hasan-d** [jsalatas/plasma-pstate#20]
Is there a way to install this widget in Linux Mint Cinnamon ? and how ?

is there an alternative to this for Cinnamon ?

**Comment by jsalatas** [comment]
Unfortunately, it cannot be used in Cinnamon. 
There is the following gnome extension but I'm not sure if that works in cinnamon 
https://extensions.gnome.org/extension/1082/cpufreq/
