### ISSUE TITLE
Save and load processor settings

### ISSUE THREAD

**Issue by akien-mga** [jsalatas/plasma-pstate#21]
I'd like to have the possibility for the plasmoid to save and load the defined processor settings in some way.

It could be that it should simply remember its previous state and restore it on boot, or there could be a system of presets that can be configured, choosing which one is the default and giving the ability to switch between them.

I'm limiting my current settings to to 85% max CPU performance and no turbo to prevent overheating and throttling on this way-too-thin-for-its-specs HP laptop I have, and currently I need to redo this configuration every time I boot.

BTW, thanks for your work on this widget, it's really convenient :)

**Comment by jsalatas** [comment]
> I'm limiting my current settings to to 85% max CPU performance and no turbo to prevent overheating and throttling on this way-too-thin-for-its-specs HP laptop I have, and currently I need to redo this configuration every time I boot.

You should probably use [TLP](https://github.com/linrunner/TLP) for that. It has plenty of settings you can customize and apply automatically during boot. 

Let's try to keep the widget simple ;)
