### ISSUE TITLE
Giant fonts on hover

### ISSUE THREAD

**Issue by alexgallotta** [jsalatas/plasma-pstate#30]
When hovering, fonts are giants and I can't find any way to reduce them
![Screenshot_20190808_173430](https://user-images.githubusercontent.com/5581237/62746149-1ca8bf00-ba03-11e9-9448-cf7e3fb52054.png)

**Comment by jsalatas** [comment]
Hmmmm.... the font-sizes are hardcoded according to what looked/looks OK in my PC :)

I'll have a second look though.... 

In the mean time, are you sure you don't have any issues with your fonts? It seems (please correct me if I'm wrong) that in general you are using a serif font, however the "C" letter (the celsius unit in temperature) seems like a non-serif (like it is substituted with some other font) :\

What distro are you using? 
What are you KDE font settings? Could you please also provide a screenshot of systemsettings -> fonts?

Thank you!!!

**Comment by alexgallotta** [comment]
Here are my fonts
![Screenshot_20190808_175343](https://user-images.githubusercontent.com/5581237/62746635-9a6dca00-ba05-11e9-879c-7b4d4092f019.png)
and here it is how it looks like when the icon opened
![Screenshot_20190808_175422](https://user-images.githubusercontent.com/5581237/62746644-a194d800-ba05-11e9-87bb-de2595e4eec6.png)
you can probably guess the difference in size between what's inside the widget and outside

**Comment by jsalatas** [comment]
Oh! OK! I see what you mean! The difference isn't so apparent using the default fonts. :)

**Comment by alexgallotta** [comment]
If this may help: reducing general font size seems to "reduce" the total size of the pop up
![Screenshot_20190808_180007](https://user-images.githubusercontent.com/5581237/62746893-bfaf0800-ba06-11e9-86ef-d18f61d49ff2.png)

**Comment by jsalatas** [comment]
could you please try now? :\

BTW: Apparently my symbol font sucks (it has the wrong metrics or something).

**Comment by alexgallotta** [comment]
I upgraded and restarted the machine, it did not work.
Anyway it's not a big deal if none else is affected
