### ISSUE TITLE
How do I ensure settings stay as they are after restarting?

### ISSUE THREAD

**Issue by UltraFuture7000** [jsalatas/plasma-pstate#32]
Hi!

This is a great widget. However, it doesn't retain my settings when I restart my computer. Is there any way I could do this?

**Comment by jsalatas** [comment]
> Is there any way I could do this?
Yeah! You can use [TLP](https://github.com/linrunner/TLP) for this. And after you have your settings restored by TLP, then you can use the widget to change these as needed. 
This is actually the main reason I created the widget: to be able to quickly tweak setting that otherwise are handled by TLP.

**Comment by UltraFuture7000** [comment]
Awesome. Thank you!
