### ISSUE TITLE
Flood in journalctl

### ISSUE THREAD

**Issue by NathanPB** [jsalatas/plasma-pstate#37]
Hello, I love that plasmoid, but its flooding my journalctl and difficulting me to view the logs from other applications.
![Desktop 1_548](https://user-images.githubusercontent.com/18128642/66709360-a2fdbc00-ed38-11e9-959f-c6893ba17808.png)

Am I doing something wrong? If so, what? Could you please do something about?

I'm running on OpenSuse Tumbleweed

Thanku

**Comment by jsalatas** [comment]
See here for work arounds
https://github.com/jsalatas/plasma-pstate/wiki/Too-many-messages-in-system-log

Any new ideas are more than welcomed :)
