### ISSUE TITLE
Manjaro and sudoers group, let's discuss a solution

### ISSUE THREAD

**Issue by Mrcuve0** [jsalatas/plasma-pstate#4]
HI! First of all I'd like to thank you for this widget, nice idea and nice realization!

So, a little background I think here is needed. 
I'm on Manjaro KDE and the plasmoid didn't work correctly: 
please take a look at [this screenshot](https://imgur.com/a/CDOwI4j).

* The sliders are on the left edge (zero position) and the values show a "N/A" value.
* The CPU values are correctly shown (percentage of usage and core frequency).
* The sliders of the CPU section can be modified but they are reverted back to zero at the next refresh.
* Finally the GPU section cannot be modified

So I started checking your script file, enabling and disabling TLP hoping for conflicts, I even tried to run it on a KDE Neon VirtualBox install (although I solved the problem before the installation completion) but nothing happened.

Finally, I checked if my user was correctly added to the sudoers group and I learnt that Arch based distros use the ```wheel``` group as a ```sudoers``` group, as pointed [here](https://imgur.com/a/CDOwI4j).

So, as pointed by the forum, I checked into the ```/etc/sudoers.d/``` folder and changed the content of the file ```99-plasma-pstate``` and changed it from
```
%sudo ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh
```
to 
```
%wheel ALL=NOPASSWD: /usr/share/plasma/plasmoids/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh
```

Now the plasmoid works correclty.

Actually, I don't know if just adding this new line to the ```99-plasma-pstate``` will solve the problem or if there's a more elegant solution: for example we could also check if the user runs on manjaro or arch and then decide what to do.

**Comment by jsalatas** [comment]
Thanks for your feedack! 

The changes I just committed should handle the issue.
