### ISSUE TITLE
Just installed. How do you run this stuff?

### ISSUE THREAD

**Issue by kvak** [jsalatas/plasma-pstate#49]
(it's all in the title. I followed the readme and installed. Nothing tells me how to run tho)

**Comment by jsalatas** [comment]
not an issue :)

**Comment by mabdelhafiz94** [comment]
It's a widget, just add it somewhere ;)

**Comment by kvak** [comment]
> It's a widget, just add it somewhere ;)

Thank, I am new to KDE. Just figured it out
