### ISSUE TITLE
Integration with Plasma project?

### ISSUE THREAD

**Issue by VladimirMikulic** [jsalatas/plasma-pstate#58]
Hi @jsalatas.

I was wondering if there are plans to merge this project with Plasma i.e. making this a default applet. In my opinion, the applet is really crucial and should be included with the normal Plasma release.

Thank you so much for this applet!

**Comment by mdedetrich** [comment]
@jsalatas 

When you say 

> Obviously some proprietary (like vendor specifics) and advanced stuff (like gpu frequencies etc) will not be merged, but after I'm done with that, I guess I'll rewrite the widget in a more proper way (eg not use sudo but kauth, etc).

What do you mean precisely? Ideally if you have an NVidia GPU with a proprietary blob KDE should detect that and show the statistics or am I missing something?
