### ISSUE TITLE
Will this and tlp clash?

### ISSUE THREAD

**Issue by Sgt-Miller** [jsalatas/plasma-pstate#60]
So I already have tlp installed, but its cli only so kinda hard to use.        
Is plasma-pstate basically a GUI for tlp? If I change something in plasma-pstate, will it also change in tlp?

**Comment by jsalatas** [comment]
You can have both. If you change something in plasma-pstate then it will be valid until you reboot your PC, or you change the power supply (plug/unplug power cord). In the last case TLP will switch to what it has been configured.

**Comment by Sgt-Miller** [comment]
Thank you
