### ISSUE TITLE
Unable to change dropdown menu options

### ISSUE THREAD

**Issue by guiodic** [jsalatas/plasma-pstate#68]
The dropdown menues don't work (governor, thermal mode) so I'm unable to change them.

Operating System: Manjaro Linux
KDE Plasma Version: 5.24.4
KDE Frameworks Version: 5.93.0
Qt Version: 5.15.3
Kernel Version: 5.17.5-1-tt (64-bit)
Graphics Platform: X11
Processors: 8 × 11th Gen Intel® Core™ i5-1135G7 @ 2.40GHz
Memory: 15.4 GiB of RAM
Graphics Processor: Mesa Intel® Xe Graphics

**Comment by jsalatas** [comment]
try running the [set_prefs.sh](https://github.com/jsalatas/plasma-pstate/blob/master/gr.ictpro.jsalatas.plasma.pstate/contents/code/set_prefs.sh) script in a terminal (you need sudo) with the relevant command options and see if that works or if you get any error messages. 

You maay also want to try the maintained fork of the widget https://github.com/frankenfruity/plasma-pstate

**Comment by guiodic** [comment]
Sorry, I use the frankendruity fork, my fault.

**Comment by jsalatas** [comment]
> Sorry, I use the frankendruity fork, my fault.

No worries! :)

Shouting out @frankenfruity who for some reason their repo doesn't have a "Issues" tab, and apparently there's no way to report issues there. ;)
